# Generated by Django 5.2.5 on 2025-08-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('saxifa', models.PositiveIntegerField(blank=True, null=True)),
                ('yili', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('narxi', models.PositiveIntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.genre')),
            ],
        ),
    ]
