# Generated by Django 5.1.6 on 2025-08-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=220)),
                ('bio', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
